### ISSUE TITLE
"Missing C library: edit" and the compiling failed

### ISSUE THREAD

**Issue by TorosFanny** [bscarlet/llvm-general#160]
I can't find `edit` library with `apt-file search` and don't know what this `edit` library is by all means. Could you tell me what this `edit` is.

**Comment by bscarlet** [comment]
It's a sometime-dependency of LLVM - llvm-general only needs it indirectly. I think you could disable LLVM's use of it by passing --enable-libedit=no when configuring LLVM.

It appears to be an alternative to the readline library with a more permissive license.

Since you mention apt-file, I assume you're using a Debian derivative. The package is called libedit. On Debian and Ubuntu, the development package you'll need is called libedit-dev.

**Comment by TorosFanny** [comment]
Thank you for your detailed reply.
