### ISSUE TITLE
Stronger typing of Instruction and Operand

### ISSUE THREAD

**Issue by tinco** [bscarlet/llvm-general#165]
This might be a step towards #65 at the moment I'm struggling with getting my code generation to be correct, and one thing that gives me difficulty is that often the asserts fail in Instruction.cpp which cause the whole process to exit and doesn't give me much in the way of debugging possibilities.

I feel a lot might be alleviated by having more strict types in the instructions (i.e. having a PointerOperand be the address of the store instruction) Have you considered if this is at all possible? Is this what you meant with #33?

**Comment by bscarlet** [comment]
llvm-general deliberately makes the opposite choice - to avoid what you're suggesting. The "llvm" package, which predates llvm-general, implemented what you describe. It worked very well for some cases, but in practice made some tasks with llvm very difficult; in essence because for some applications it winds up being quite burdensome to express the proof that a program's use of llvm is safe in the Haskell type system. When accomplished, such a proof is beautiful and valuable - and in some circumstances essential - but I do not want to restrict llvm-general to require one (hence the name - "general" as in usable for much of what one might do with llvm safe, wise, or crazy). 

It would be an interesting and likely valuable exercise to re-implement the safe API of that library in terms of llvm-general, but I think that would best be done as a separate layer.

As a practical matter, are you using a build of llvm with asserts turned on? Without them it is particularly opaque.
