### ISSUE TITLE
Segmentation fault when lowering to LLVM IR

### ISSUE THREAD

**Issue by ghost** [bscarlet/llvm-general#166]
Hi!

I seem to get a segmentation fault when attempting to lower LLVM-ASTs to LLVM-IR using LLVM-General.  

llc --version
LLVM (http://llvm.org/):
  LLVM version 3.5.2
  Optimized build.
  Built Dec  5 2015 (17:41:16).
  Default target: x86_64-unknown-linux-gnu
  Host CPU: corei7-avx

from ghc-pkg list
 ...
    llvm-general-3.5.1.2
   llvm-general-pure-3.5.1.0

Could the problem be the difference in version numbers?  I cabal update, but there doesn't seem to be a new package for llvm-general-pure available.

Any advice would be greatly appreciated.

**Comment by bscarlet** [comment]
The versions are okay.

Can you share the code which causes the problem? Please trim it down to a somewhat small example.

**Comment by caneroj1** [comment]
I'm seeing a segfault too..

I used gdb to look at what was going on, and it segfaulted here: `llvm::LoadInst::LoadInst(llvm::Value*, char const*, bool, llvm::Instruction*)`.

I can try and pare what I'm doing down to a small example, but I'm basically working through this tutorial: http://www.stephendiehl.com/llvm/.

My versions are the same was what's listed in the above comment, and my llvm is 3.5.

**Comment by bscarlet** [comment]
Please provide enough information to specify the problem.

**Comment by caneroj1** [comment]
[This code](https://gist.github.com/caneroj1/8a15d034e3d7b8ae560062774f98b576) causes a segmentation fault.

Please let me know if you need more information. 

GHC version = Version 7.10.2.

**Comment by bscarlet** [comment]
Granted it's bad you get a segfault instead of an error message, but your primary problem is with the LLVM code you're trying to generate. The $var name you're using as the address to (resp. from) which to store (resp. load) is never defined.

Is your LLVM library compiled with asserts turned on? If not, I recommend you build yourself such a version.

**Comment by bscarlet** [comment]
Actually, before you even get as far as the llvm-general code that should check to see if $var (which might have been a forward reference) ever got defined, you'll still be trying to build the load and store instructions with their "address" operand as the not-yet-defined value $var of type double.

With my LLVM build which as asserts on, I get:
test: Instructions.cpp:1082: void llvm::StoreInst::AssertOK(): Assertion `getOperand(1)->getType()->isPointerTy() && "Ptr must have pointer type!"' failed.

When I (slightly) correct your code, changing the type you give for $var to "ptr double", I correctly get an error from my own check. You still have other errors.

If you use the record constructor syntax for instructions, rather than the positional/curried syntax, it's clearer that the field is named "address", which is supposed to help you understand what that assert checks.

**Comment by bscarlet** [comment]
JonathanGallagher, please re-open if you've got a reproducible test case.

**Comment by caneroj1** [comment]
Thanks a lot for your help. I was able to figure out the problem and correct the code generation. Hopefully the seg fault is an easy fix!
