### ISSUE TITLE
github repository seems to lag behind Hackage

### ISSUE THREAD

**Issue by amigalemming** [bscarlet/llvm-general#174]
Hackage has llvm-general-3.5.1.2, whereas here in the repo I see only 3.5.0.0.

**Comment by bscarlet** [comment]
Sounds like you're looking at the master branch. While that's a good intuitive guess, it's not the branch or tag specified in the cabal file of the version(s) on hackage. Those point you to the llvm-3.5 branch, where you'll find the version corresponding to the hackage release.

"master" is indeed currently lagging the 3.5 branch. Because most work on llvm-general has recently been about trying to catch up with LLVM releases rather than work on llvm-general itself, the action has been on the release branches - llvm-3.5 and the not-yet-released-on-hackage llvm-3.8.

**Comment by amigalemming** [comment]
On Sat, 6 Aug 2016, Benjamin S. Scarlet wrote:

> Sounds like you're looking at the master branch. While that's a good intuitive guess, it's not the branch or tag
> specified in the cabal file of the version(s) on hackage. Those point you to the llvm-3.5 branch, where you'll find the
> version corresponding to the hackage release.

I did

$ cabal get --source-repository=head llvm-general

and compared with what GitHub shows as main page.

In contrast to that:

$ cabal get --source-repository=this llvm-general
git: clone "git://github.com/bscarlet/llvm-general.git"
Cloning into 'llvm-general'...
remote: Counting objects: 11626, done.
remote: Total 11626 (delta 0), reused 0 (delta 0), pack-reused 11626
Receiving objects: 100% (11626/11626), 2.75 MiB | 646 KiB/s, done.
Resolving deltas: 100% (7958/7958), done.
error: unknown option `branch'
usage: git checkout [options] <branch>
    or: git checkout [options] [<branch>] -- <file>...

...

cabal: Couldn't fork package llvm-general-3.5.1.2

Despite the error message this brings me to the version 3.5.1.2.

**Comment by bscarlet** [comment]
I don't use "cabal get", just git. The git command shown on the hackage page works for me:

git clone git://github.com/bscarlet/llvm-general.git -b llvm-3.5

Why is the command "cabal get" is running different?

**Comment by amigalemming** [comment]
On Sat, 6 Aug 2016, Benjamin S. Scarlet wrote:

> I don't use "cabal get", just git.

I use 'cabal' because it is the same for all versioning systems.

> The git command shown on the hackage page works for me:
> 
> git clone git://github.com/bscarlet/llvm-general.git -b llvm-3.5

Works for me, too.

> Why is the command "cabal get" is running different?

I have no idea.

**Comment by bscarlet** [comment]
If "cabal get" is running commands that git doesn't recognize, that seems like a question for the cabal folks. Please consider asking them.
